apiVersion: v1alpha1
kind: "Role"
metadata:
  name: plugin-uni-halo-role-template-view-banner
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-admin: "true"
  annotations:
    rbac.authorization.halo.run/module: "UniHalo 轮播管理"
    rbac.authorization.halo.run/display-name: "轮播管理查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:uni-halo:banner:view"]
rules:
  - apiGroups: [ "console.api.unihalo.ialley.cn" ]
    resources:
      - "plugins/plugin-uni-halo/banners"
      - "plugins/plugin-uni-halo/banners/*"
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: "Role"
metadata:
  name: plugin-uni-halo-role-template-manage-banner
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-admin: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "plugin-uni-halo-role-template-view-banner" ]
    rbac.authorization.halo.run/module: "UniHalo 轮播管理"
    rbac.authorization.halo.run/display-name: "轮播管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:uni-halo:banner:manage"]
rules:
  - apiGroups: [ "console.api.unihalo.ialley.cn" ]
    resources:
      - "plugins/plugin-uni-halo/banners"
      - "plugins/plugin-uni-halo/banners/*"
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
