apiVersion: v1alpha1
kind: "Role"
metadata:
  name: plugin-uni-halo-role-template-view-audit-data
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-admin: "true"
  annotations:
    rbac.authorization.halo.run/module: "UniHalo 审核配置"
    rbac.authorization.halo.run/display-name: "审核配置查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:uni-halo:audit-data:view"]
rules:
  - apiGroups: [ "console.api.unihalo.ialley.cn" ]
    resources:
      - "plugins/plugin-uni-halo/audit-data"
      - "plugins/plugin-uni-halo/audit-data/*"
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: "Role"
metadata:
  name: plugin-uni-halo-role-template-manage-audit-data
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-admin: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "plugin-uni-halo-role-template-view-audit-data" ]
    rbac.authorization.halo.run/module: "UniHalo 审核配置"
    rbac.authorization.halo.run/display-name: "审核配置管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:uni-halo:audit-data:manage"]
rules:
  - apiGroups: [ "console.api.unihalo.ialley.cn" ]
    resources:
      - "plugins/plugin-uni-halo/audit-data"
      - "plugins/plugin-uni-halo/audit-data/*"
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
